services:
  - type: web
    name: yemot-transcription-sendlib
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app_sendlib.py
    envVars:
      - key: YMOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SENDLIB_API_KEY
        sync: false
      - key: SENDLIB_FROM_EMAIL
        sync: false
