services:
  - type: web
    name: yemot-transcription-lettr
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app_lettr.py
    envVars:
      - key: YMOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: LETTR_API_KEY
        sync: false
      - key: LETTR_FROM_EMAIL
        sync: false
